context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Bose Equalizer Sink"
            media.name       = "Bose Equalizer Sink"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq_band_1
                        label = bq_peaking
                        control = { "Freq" = 42.8233 "Q" = 4.65045 "Gain" = -6.09 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_2
                        label = bq_peaking
                        control = { "Freq" = 53.141 "Q" = 4.65045 "Gain" = -8 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_3
                        label = bq_peaking
                        control = { "Freq" = 65.9447 "Q" = 4.65045 "Gain" = -10.63 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_4
                        label = bq_peaking
                        control = { "Freq" = 81.8333 "Q" = 4.65045 "Gain" = -11.11 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_5
                        label = bq_peaking
                        control = { "Freq" = 101.55 "Q" = 4.65045 "Gain" = -9.2 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_6
                        label = bq_peaking
                        control = { "Freq" = 126.017 "Q" = 4.65045 "Gain" = -4.42 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_7
                        label = bq_peaking
                        control = { "Freq" = 156.379 "Q" = 4.65045 "Gain" = -1.52 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_8
                        label = bq_peaking
                        control = { "Freq" = 6136.63 "Q" = 4.65045 "Gain" = -6.93 }
                    }
                    {
                        type  = builtin
                        name  = eq_band_9
                        label = bq_peaking
                        control = { "Freq" = 7615.17 "Q" = 4.65045 "Gain" = -10.03 }
                    }
                ]
                links = [
                    { output = "eq_band_1:Out" input = "eq_band_2:In" }
                    { output = "eq_band_2:Out" input = "eq_band_3:In" }
                    { output = "eq_band_3:Out" input = "eq_band_4:In" }
                    { output = "eq_band_4:Out" input = "eq_band_5:In" }
                    { output = "eq_band_5:Out" input = "eq_band_6:In" }
                    { output = "eq_band_6:Out" input = "eq_band_7:In" }
                    { output = "eq_band_7:Out" input = "eq_band_8:In" }
                    { output = "eq_band_8:Out" input = "eq_band_9:In" }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "effect_input.bose_eq"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "effect_output.bose_eq"
                node.passive = true
            }
        }
    }
]
