set-option -g prefix C-t
unbind-key C-b
bind-key t send-prefix
bind-key C-t last-window
bind-key x lock-client
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key A command-prompt "rename-window '%%'"
bind-key H resize-pane -L
bind-key J resize-pane -D
bind-key K resize-pane -U
bind-key L resize-pane -R
bind-key R source-file ~/.tmux.conf
bind-key S set-window-option synchronize-panes
bind-key M-u unlink-window

# tmux 1.9+, lower will get to /
# https://stackoverflow.com/a/22102261/296473
bind-key c new-window -c '#{pane_current_path}'

# https://lug.ustc.edu.cn/planet/2025/07/how-to-use-tmux/
# 按 Ctrl-F12 切换到内嵌 tmux，在 macos 里需要系统设置中取消 F12 占用
# 1. prefix 为 None，不再拦截快捷键
# 2. key-table 为 off，下面再绑定 off 下的 F12，使之能退出内嵌模式
# 3. 改变 statusbar 颜色，以便知道已进入内嵌模式
# 4. 如果处于特殊模式，退出
bind -T root C-F12 \
  set prefix None \;\
  set key-table off \;\
  set status-style bg=colour235 \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

# 在 off 表里绑定 F12，恢复之前的设置，以退出该模式
bind -T off C-F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S

# 状态栏格式
# with -b tmux will wait to exit; we exit when we fail to call tmux
if-shell "accurate-time tmux </dev/null >/dev/null 2>&1" {
  set -g status-interval 0
} {
  set -g status-interval 1
  set -g status-right "#[fg=red]#(awk '{print $1, $2, $3}' /proc/loadavg) #[fg=colour15]%Y-%m-%d %H:%M:%S"
}
set -g status-left ""
set -g status-style "fg=cyan bg=colour8" #灰色背景
set -g message-style "fg=colour10 bg=colour8"
set-window-option -g window-status-format "#I#{?window_flags,#{window_flags}, }#W"
set-window-option -g window-status-current-format "#[fg=colour10]#I#F#W"
set-window-option -g mode-style "fg=green bg=colour15"
set-window-option -g xterm-keys on

set -g set-titles on
set -g set-titles-string "#S:#I:#W"
set -g lock-command vlock
#For vim
set -sg escape-time 50
set -g status-keys "emacs"
set-window-option -g mode-keys vi
set-window-option -g alternate-screen on
# allow escape sequence to change title
set-window-option -g allow-rename on
set -g renumber-windows on
set -g history-limit 10000

set -g default-terminal "tmux-256color"
set -ga terminal-features "*:hyperlinks"
# For true colors
# https://gist.github.com/XVilka/8346728
set -sa terminal-overrides "xterm-256color:Tc"
set -sa terminal-overrides "alacritty:Tc"
# SGR 53 (overline)
set -sa terminal-overrides '*:Smol=\E[53m'
# styled underscore
set -sa terminal-overrides '*:Smulx=\E[4::%p1%dm'
# underscore colors
set -sa terminal-overrides '*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -sga update-environment " DBUS_SESSION_BUS_ADDRESS XMODIFIERS GTK_IM_MODULE QT_IM_MODULE FCITX_SOCKET COLORTERM"
set -sga update-environment " GDK_SCALE GDK_DPI_SCALE XCURSOR_SIZE XCURSOR_THEME QT_WAYLAND_FORCE_DPI"
set -sga update-environment " WAYLAND_DISPLAY QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE"
set-environment -g GVIM_ENABLE_WAYLAND 1 
set-environment -g RUSTICL_ENABLE iris
set-environment -g VK_LOADER_DRIVERS_DISABLE nvidia_icd.json

set-environment -gu INVOCATION_ID
set-environment -gu JOURNAL_STREAM
set-environment -gu MANAGERPID
set-environment -gu MEMORY_PRESSURE_WATCH
set-environment -gu MEMORY_PRESSURE_WRITE
set-environment -gu SYSTEMD_EXEC_PID
