#!/usr/bin/python3

import sys
import os
import json
import httpx
import time

import toml

ENDPOINT = 'https://api.waqi.info/feed/%(city)s/?token=%(token)s'

client = httpx.Client(http2=True)

def color(aqi):
  if aqi <= 50:
    s = 'green'
  elif aqi <= 100:
    s = 'yellow'
  elif aqi <= 150:
    s = 'orange'
  elif aqi <= 200:
    s = 'red'
  elif aqi <= 300:
    s = 'purple'
  else:
    s = 'maroon'
  return s

def wait_some_time():
  deadline = time.time() + 13 * 60
  while True:
    time.sleep(60)
    if time.time() > deadline:
      return

def main():
  mydir = os.path.dirname(__file__)
  with open(os.path.join(mydir, 'secrets.toml')) as f:
    config = toml.load(f)['aqi']

  if len(sys.argv) == 2 and sys.argv[1] == 'open-url':
    url = 'https://aqicn.org/city/%s/cn' % config['city']
    import subprocess
    subprocess.check_call(['xdg-open', url])
    return

  if len(sys.argv) == 1:
    run(config)
    return

  sys.exit('bad argument')

def run(config):
  url = ENDPOINT % config
  output = {"text": "", "tooltip": "", "class": "", "percentage": 0 }
  while True:
    data = fetch_data(url)
    output['text'] = f'{data["dominentpol"]} {data["aqi"]}'
    output['percentage'] = data['aqi']
    output['tooltip'] = f'updated at {data["time"]["s"]}'
    output['class'] = color(data['aqi'])
    json.dump(output, sys.stdout)
    print(flush=True)
    wait_some_time()

def fetch_data(url):
  res = client.get(url)
  j = res.json()
  return j['data']

if __name__ == '__main__':
  main()
